// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "PlayerSpawned.g.generated.h"

// Reducer arguments struct for PlayerSpawned
USTRUCT(BlueprintType)
struct CLIENT_UNREAL_API FPlayerSpawnedArgs
{
    GENERATED_BODY()

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 CharacterId = 0;

    FPlayerSpawnedArgs() = default;

    FPlayerSpawnedArgs(uint32 InCharacterId)
        : CharacterId(InCharacterId)
    {}


    FORCEINLINE bool operator==(const FPlayerSpawnedArgs& Other) const
    {
        return CharacterId == Other.CharacterId;
    }
    FORCEINLINE bool operator!=(const FPlayerSpawnedArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FPlayerSpawnedArgs, CharacterId);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class CLIENT_UNREAL_API UPlayerSpawnedReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 CharacterId = 0;

};


