// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "ModuleBindings/Types/TransformType.g.h"
#include "UpdatePlayerInput.g.generated.h"

// Reducer arguments struct for UpdatePlayerInput
USTRUCT(BlueprintType)
struct CLIENT_UNREAL_API FUpdatePlayerInputArgs
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    FTransformType NewTransform;

    FUpdatePlayerInputArgs() = default;

    FUpdatePlayerInputArgs(const FTransformType& InNewTransform)
        : NewTransform(InNewTransform)
    {}


    FORCEINLINE bool operator==(const FUpdatePlayerInputArgs& Other) const
    {
        return NewTransform == Other.NewTransform;
    }
    FORCEINLINE bool operator!=(const FUpdatePlayerInputArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FUpdatePlayerInputArgs, NewTransform);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class CLIENT_UNREAL_API UUpdatePlayerInputReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FTransformType NewTransform;

};


