// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "ModuleBindings/Types/PlayerCharacterType.g.h"
#include "Tables/RemoteTable.h"
#include "DBCache/WithBsatn.h"
#include "DBCache/TableHandle.h"
#include "DBCache/TableCache.h"
#include "PlayerCharacterTable.g.generated.h"

UCLASS(Blueprintable)
class CLIENT_UNREAL_API UPlayerCharacterCharacterIdUniqueIndex : public UObject
{
    GENERATED_BODY()

private:
    // Declare an instance of your templated helper.
    // It's private because the UObject wrapper will expose its functionality.
    FUniqueIndexHelper<FPlayerCharacterType, uint32, FTableCache<FPlayerCharacterType>> CharacterIdIndexHelper;

public:
    UPlayerCharacterCharacterIdUniqueIndex()
        // Initialize the helper with the specific unique index name
        : CharacterIdIndexHelper("character_id") {
    }

    /**
     * Finds a PlayerCharacter by their unique characterid.
     * @param Key The characterid to search for.
     * @return The found FPlayerCharacterType, or a default-constructed FPlayerCharacterType if not found.
     */
    // NOTE: Not exposed to Blueprint because uint32 types are not Blueprint-compatible
    FPlayerCharacterType Find(uint32 Key)
    {
        // Simply delegate the call to the internal helper
        return CharacterIdIndexHelper.FindUniqueIndex(Key);
    }

    // A public setter to provide the cache to the helper after construction
    // This is a common pattern when the cache might be created or provided by another system.
    void SetCache(TSharedPtr<const FTableCache<FPlayerCharacterType>> InPlayerCharacterCache)
    {
        CharacterIdIndexHelper.Cache = InPlayerCharacterCache;
    }
};
/***/

UCLASS(Blueprintable)
class UPlayerCharacterEntityIdIndex : public UObject
{
    GENERATED_BODY()

public:
    TArray<FPlayerCharacterType> Filter(const uint32& EntityId) const
    {
        TArray<FPlayerCharacterType> OutResults;

        LocalCache->FindByMultiKeyBTreeIndex<TTuple<uint32>>(
            OutResults,
            TEXT("entity_id"),
            MakeTuple(EntityId)
        );

        return OutResults;
    }

    void SetCache(TSharedPtr<FTableCache<FPlayerCharacterType>> InCache)
    {
        LocalCache = InCache;
    }

private:
    // NOTE: Not exposed to Blueprint because some parameter types are not Blueprint-compatible
    void FilterEntityId(TArray<FPlayerCharacterType>& OutResults, const uint32& EntityId)
    {
        OutResults = Filter(EntityId);
    }

    TSharedPtr<FTableCache<FPlayerCharacterType>> LocalCache;
};

UCLASS(Blueprintable)
class UPlayerCharacterPlayerIdIndex : public UObject
{
    GENERATED_BODY()

public:
    TArray<FPlayerCharacterType> Filter(const uint32& PlayerId) const
    {
        TArray<FPlayerCharacterType> OutResults;

        LocalCache->FindByMultiKeyBTreeIndex<TTuple<uint32>>(
            OutResults,
            TEXT("player_id"),
            MakeTuple(PlayerId)
        );

        return OutResults;
    }

    void SetCache(TSharedPtr<FTableCache<FPlayerCharacterType>> InCache)
    {
        LocalCache = InCache;
    }

private:
    // NOTE: Not exposed to Blueprint because some parameter types are not Blueprint-compatible
    void FilterPlayerId(TArray<FPlayerCharacterType>& OutResults, const uint32& PlayerId)
    {
        OutResults = Filter(PlayerId);
    }

    TSharedPtr<FTableCache<FPlayerCharacterType>> LocalCache;
};

UCLASS(BlueprintType)
class CLIENT_UNREAL_API UPlayerCharacterTable : public URemoteTable
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly)
    UPlayerCharacterCharacterIdUniqueIndex* CharacterId;

    UPROPERTY(BlueprintReadOnly)
    UPlayerCharacterEntityIdIndex* EntityId;

    UPROPERTY(BlueprintReadOnly)
    UPlayerCharacterPlayerIdIndex* PlayerId;

    void PostInitialize();

    /** Update function for player_characters table*/
    FTableAppliedDiff<FPlayerCharacterType> Update(TArray<FWithBsatn<FPlayerCharacterType>> InsertsRef, TArray<FWithBsatn<FPlayerCharacterType>> DeletesRef);

    /** Number of subscribed rows currently in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    int32 Count() const;

    /** Return all subscribed rows in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    TArray<FPlayerCharacterType> Iter() const;

    // Table Events
    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnPlayerCharacterInsert,
        const FEventContext&, Context,
        const FPlayerCharacterType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams( 
        FOnPlayerCharacterUpdate,
        const FEventContext&, Context,
        const FPlayerCharacterType&, OldRow,
        const FPlayerCharacterType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnPlayerCharacterDelete,
        const FEventContext&, Context,
        const FPlayerCharacterType&, DeletedRow);

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnPlayerCharacterInsert OnInsert;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnPlayerCharacterUpdate OnUpdate;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnPlayerCharacterDelete OnDelete;

private:
    const FString TableName = TEXT("player_characters");

    TSharedPtr<UClientCache<FPlayerCharacterType>> Data;
};
