// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#include "ModuleBindings/Tables/PlayerCharacterTable.g.h"
#include "DBCache/UniqueIndex.h"
#include "DBCache/BTreeUniqueIndex.h"
#include "DBCache/ClientCache.h"
#include "DBCache/TableCache.h"

void UPlayerCharacterTable::PostInitialize()
{
    /** Client cache init and setting up indexes*/
    Data = MakeShared<UClientCache<FPlayerCharacterType>>();

    TSharedPtr<FTableCache<FPlayerCharacterType>> PlayerCharacterTable = Data->GetOrAdd(TableName);
    PlayerCharacterTable->AddUniqueConstraint<uint32>("character_id", [](const FPlayerCharacterType& Row) -> const uint32& {
        return Row.CharacterId; });

    CharacterId = NewObject<UPlayerCharacterCharacterIdUniqueIndex>(this);
    CharacterId->SetCache(PlayerCharacterTable);

    // Register a new multi-key B-Tree index named "entity_id" on the PlayerCharacterTable.
    PlayerCharacterTable->AddMultiKeyBTreeIndex<TTuple<uint32>>(
        TEXT("entity_id"),
        [](const FPlayerCharacterType& Row)
        {
            // This tuple is stored in the B-Tree index for fast composite key lookups.
            return MakeTuple(Row.EntityId);
        }
    );

    EntityId = NewObject<UPlayerCharacterEntityIdIndex>(this);
    EntityId->SetCache(PlayerCharacterTable);

    // Register a new multi-key B-Tree index named "player_id" on the PlayerCharacterTable.
    PlayerCharacterTable->AddMultiKeyBTreeIndex<TTuple<uint32>>(
        TEXT("player_id"),
        [](const FPlayerCharacterType& Row)
        {
            // This tuple is stored in the B-Tree index for fast composite key lookups.
            return MakeTuple(Row.PlayerId);
        }
    );

    PlayerId = NewObject<UPlayerCharacterPlayerIdIndex>(this);
    PlayerId->SetCache(PlayerCharacterTable);

    /***/
}

FTableAppliedDiff<FPlayerCharacterType> UPlayerCharacterTable::Update(TArray<FWithBsatn<FPlayerCharacterType>> InsertsRef, TArray<FWithBsatn<FPlayerCharacterType>> DeletesRef)
{
    FTableAppliedDiff<FPlayerCharacterType> Diff = BaseUpdate<FPlayerCharacterType>(InsertsRef, DeletesRef, Data, TableName);

    Diff.DeriveUpdatesByPrimaryKey<uint32>(
        [](const FPlayerCharacterType& Row) 
        {
            return Row.CharacterId; 
        }
    );

    return Diff;
}

int32 UPlayerCharacterTable::Count() const
{
    return GetRowCountFromTable<FPlayerCharacterType>(Data, TableName);
}

TArray<FPlayerCharacterType> UPlayerCharacterTable::Iter() const
{
    return GetAllRowsFromTable<FPlayerCharacterType>(Data, TableName);
}
