// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ClientUnrealOptionalString.g.generated.h"

USTRUCT(BlueprintType)
struct CLIENT_UNREAL_API FClientUnrealOptionalString
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    bool bHasValue = false;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB", meta = (EditCondition = "bHasValue"))
    FString Value;

    FClientUnrealOptionalString() = default;

    explicit FClientUnrealOptionalString(const FString& InValue)
        : bHasValue(true), Value(InValue) {}

    bool IsSet() const { return bHasValue; }
    void Reset() { bHasValue = false; }

    FORCEINLINE bool operator==(const FClientUnrealOptionalString& Other) const
    {
        if (bHasValue != Other.bHasValue) return false;
        return !bHasValue || Value == Other.Value;
    }

    FORCEINLINE bool operator!=(const FClientUnrealOptionalString& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FClientUnrealOptionalString.
 * Hashes the HasValue flag and the Value if present.
 * @param Optional The FClientUnrealOptionalString instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FClientUnrealOptionalString& Optional)
{
    uint32 Hash = GetTypeHash(Optional.bHasValue);
    if (Optional.bHasValue)
    {
        Hash = HashCombine(Hash, GetTypeHash(Optional.Value));
    }
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FClientUnrealOptionalString);

    UE_SPACETIMEDB_OPTIONAL(FClientUnrealOptionalString, bHasValue, Value);
}
