// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/Optionals/ClientUnrealOptionalString.g.h"
#include "ModuleBindings/Optionals/ClientUnrealOptionalUInt32.g.h"
#include "ConfigType.g.generated.h"

USTRUCT(BlueprintType)
struct CLIENT_UNREAL_API FConfigType
{
    GENERATED_BODY()

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 Id = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FString BuildVersion;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FClientUnrealOptionalString FeatureFlags;

    // NOTE: FClientUnrealOptionalUInt32 field not exposed to Blueprint due to non-blueprintable elements
    FClientUnrealOptionalUInt32 GlobalMaxPlayers;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FClientUnrealOptionalString AdminMessage;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FClientUnrealOptionalString AssetManifestUrl;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FClientUnrealOptionalString LastUpdatedAt;

    FORCEINLINE bool operator==(const FConfigType& Other) const
    {
        return Id == Other.Id && BuildVersion == Other.BuildVersion && FeatureFlags == Other.FeatureFlags && GlobalMaxPlayers == Other.GlobalMaxPlayers && AdminMessage == Other.AdminMessage && AssetManifestUrl == Other.AssetManifestUrl && LastUpdatedAt == Other.LastUpdatedAt;
    }

    FORCEINLINE bool operator!=(const FConfigType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FConfigType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param ConfigType The FConfigType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FConfigType& ConfigType)
{
    uint32 Hash = GetTypeHash(ConfigType.Id);
    Hash = HashCombine(Hash, GetTypeHash(ConfigType.BuildVersion));
    Hash = HashCombine(Hash, GetTypeHash(ConfigType.FeatureFlags));
    Hash = HashCombine(Hash, GetTypeHash(ConfigType.GlobalMaxPlayers));
    Hash = HashCombine(Hash, GetTypeHash(ConfigType.AdminMessage));
    Hash = HashCombine(Hash, GetTypeHash(ConfigType.AssetManifestUrl));
    Hash = HashCombine(Hash, GetTypeHash(ConfigType.LastUpdatedAt));
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FConfigType);

    UE_SPACETIMEDB_STRUCT(FConfigType, Id, BuildVersion, FeatureFlags, GlobalMaxPlayers, AdminMessage, AssetManifestUrl, LastUpdatedAt);
}
