// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/Types/TransformType.g.h"
#include "EntityType.g.generated.h"

USTRUCT(BlueprintType)
struct CLIENT_UNREAL_API FEntityType
{
    GENERATED_BODY()

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 EntityId = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FString EntityType;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FTransformType Transform;

    FORCEINLINE bool operator==(const FEntityType& Other) const
    {
        return EntityId == Other.EntityId && EntityType == Other.EntityType && Transform == Other.Transform;
    }

    FORCEINLINE bool operator!=(const FEntityType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FEntityType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param EntityType The FEntityType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FEntityType& EntityType)
{
    uint32 Hash = GetTypeHash(EntityType.EntityId);
    Hash = HashCombine(Hash, GetTypeHash(EntityType.EntityType));
    Hash = HashCombine(Hash, GetTypeHash(EntityType.Transform));
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FEntityType);

    UE_SPACETIMEDB_STRUCT(FEntityType, EntityId, EntityType, Transform);
}
