// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/Types/TransformType.g.h"
#include "PlayerCharacterType.g.generated.h"

USTRUCT(BlueprintType)
struct CLIENT_UNREAL_API FPlayerCharacterType
{
    GENERATED_BODY()

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 CharacterId = 0;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 PlayerId = 0;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 EntityId = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FString DisplayName;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FTransformType Transform;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    bool NeedsSpawn = false;

    FORCEINLINE bool operator==(const FPlayerCharacterType& Other) const
    {
        return CharacterId == Other.CharacterId && PlayerId == Other.PlayerId && EntityId == Other.EntityId && DisplayName == Other.DisplayName && Transform == Other.Transform && NeedsSpawn == Other.NeedsSpawn;
    }

    FORCEINLINE bool operator!=(const FPlayerCharacterType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FPlayerCharacterType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param PlayerCharacterType The FPlayerCharacterType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FPlayerCharacterType& PlayerCharacterType)
{
    uint32 Hash = GetTypeHash(PlayerCharacterType.CharacterId);
    Hash = HashCombine(Hash, GetTypeHash(PlayerCharacterType.PlayerId));
    Hash = HashCombine(Hash, GetTypeHash(PlayerCharacterType.EntityId));
    Hash = HashCombine(Hash, GetTypeHash(PlayerCharacterType.DisplayName));
    Hash = HashCombine(Hash, GetTypeHash(PlayerCharacterType.Transform));
    Hash = HashCombine(Hash, GetTypeHash(PlayerCharacterType.NeedsSpawn));
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FPlayerCharacterType);

    UE_SPACETIMEDB_STRUCT(FPlayerCharacterType, CharacterId, PlayerId, EntityId, DisplayName, Transform, NeedsSpawn);
}
