// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "TransformType.g.generated.h"

USTRUCT(BlueprintType)
struct CLIENT_UNREAL_API FTransformType
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    float X = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    float Y = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    float Z = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    float Yaw = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    float Pitch = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    float Roll = 0.0f;

    FORCEINLINE bool operator==(const FTransformType& Other) const
    {
        return X == Other.X && Y == Other.Y && Z == Other.Z && Yaw == Other.Yaw && Pitch == Other.Pitch && Roll == Other.Roll;
    }

    FORCEINLINE bool operator!=(const FTransformType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FTransformType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param TransformType The FTransformType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FTransformType& TransformType)
{
    uint32 Hash = GetTypeHash(TransformType.X);
    Hash = HashCombine(Hash, GetTypeHash(TransformType.Y));
    Hash = HashCombine(Hash, GetTypeHash(TransformType.Z));
    Hash = HashCombine(Hash, GetTypeHash(TransformType.Yaw));
    Hash = HashCombine(Hash, GetTypeHash(TransformType.Pitch));
    Hash = HashCombine(Hash, GetTypeHash(TransformType.Roll));
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FTransformType);

    UE_SPACETIMEDB_STRUCT(FTransformType, X, Y, Z, Yaw, Pitch, Roll);
}
